import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const models = [
  "admin",
  "classOfficer",
  "classSchedule",
  "announcement",
  "galleryAlbum",
  "galleryPhoto",
  "classMember",
  "calendarEvent",
] as const;

function esc(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (v instanceof Date) {
    return `'${v.toISOString().slice(0, 19).replace("T", " ")}.000'`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  const lines: string[] = [
    "-- Data dump generated by scripts/dump-db.ts (data only)",
    "SET NAMES utf8mb4;",
  ];

  for (const m of models) {
    const table = m.charAt(0).toUpperCase() + m.slice(1);
    const rows = await (prisma as unknown as Record<string, { findMany: (args: object) => Promise<Record<string, unknown>[]> }>)[m].findMany({ orderBy: { id: "asc" } });
    if (rows.length === 0) {
      console.error(`-- ${table}: 0 rows`);
      continue;
    }
    const cols = Object.keys(rows[0]);
    const colSql = cols.map((c) => `\`${c}\``).join(", ");
    for (const r of rows) {
      const vals = cols.map((c) => esc(r[c])).join(", ");
      lines.push(`INSERT INTO \`${table}\` (${colSql}) VALUES (${vals});`);
    }
    console.error(`-- ${table}: ${rows.length} rows`);
  }

  console.log(lines.join("\n"));
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
